name: "build"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: takutakahashi/github-actions/.github/workflows/ghcr.yaml@main
    with:
      image: takutakahashi/localport:latest
